"""Build a portable offline evidence viewer; no server, dependencies or remote assets."""
import json, html
from pipeline import ROOT, fitz

def main():
    records=json.loads((ROOT/'data/connections.json').read_text(encoding='utf-8'))
    coverage=json.loads((ROOT/'data/coverage.json').read_text(encoding="utf-8"))
    manifest=json.loads((ROOT/'sources/manifest.json').read_text(encoding="utf-8"))
    (ROOT/'previews').mkdir(exist_ok=True)
    for m in manifest:
        page=fitz.open(ROOT/m['file'])[0]
        m['width']=page.rect.width;m['height']=page.rect.height
        m['preview']='previews/'+m['core']+'.png'
        page.get_pixmap(matrix=fitz.Matrix(1800/page.rect.width,1800/page.rect.width)).save(ROOT/m['preview'])
    payload=json.dumps({'records':records,'maps':manifest,'coverage':coverage},ensure_ascii=False).replace('<','\\u003c')
    template='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MejorCercanías · Evidencia de conexiones</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f7;color:#172e42;font:15px/1.5 system-ui,sans-serif}header{background:#112e40;color:white;padding:24px 32px}h1{margin:0;font-size:28px}h2{font-size:18px}header p{margin:7px 0;color:#d2e2e9}.stats{display:flex;gap:12px;flex-wrap:wrap;padding:18px 32px}.stat{background:white;border:1px solid #d7e0e4;border-radius:10px;padding:12px 20px}.stat b{display:block;font-size:25px;color:#006b68}.toolbar{display:flex;gap:12px;padding:0 32px 18px;flex-wrap:wrap}select,input{font:inherit;padding:10px;border:1px solid #bbcbd1;border-radius:6px;min-width:180px}input{flex:1}main{display:grid;grid-template-columns:minmax(480px,1.4fr) minmax(400px,1fr);gap:20px;padding:0 32px 24px}.panel{background:white;border-radius:10px;border:1px solid #d7e0e4;padding:18px;min-width:0}.map{position:relative}.map img{width:100%;display:block}.map svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.map rect{fill:#ffdf4233;stroke:#be3d16;stroke-width:2}.source{font-size:13px;overflow-wrap:anywhere}.results{max-height:600px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #e1e7eb;vertical-align:top}th{position:sticky;top:0;background:#eaf1f3}tr[data-id]{cursor:pointer}tr[data-id]:hover,tr.selected{background:#e8f5f3}.badge{display:inline-block;background:#e3efed;border-radius:4px;padding:2px 6px;font-size:11px}.detail{padding:12px;background:#f2f6f7;border-radius:6px;margin-top:14px}.detail p{margin:5px 0}.note{background:#fff3d9;border-left:4px solid #e5b647;padding:12px 16px}a{color:#006a89}footer{margin:0 32px 30px}details{margin-top:12px}code{background:#edf1f4;padding:2px 4px}pre{white-space:pre-wrap}button{border:0;background:none;color:#006a89;cursor:pointer;font:inherit;padding:0;text-align:left}@media(max-width:1000px){main{grid-template-columns:1fr}.results{max-height:420px}.toolbar,.stats,main{padding-left:14px;padding-right:14px}header{padding:20px 14px}}
</style><header><h1>MejorCercanías</h1><p>Inventario cartográfico y cruce GTFS · Captura: 3 de octubre de 2026 · Fuentes: Renfe</p></header>
<div class="stats"><div class="stat"><b>15</b>mapas revisados</div><div class="stat"><b id="total"></b>observaciones revisadas</div><div class="stat"><b>5</b>enlaces a pie entre estaciones</div><div class="stat"><b>21</b>filas del transfers.txt</div></div>
<div class="toolbar"><select id="core" aria-label="Núcleo"></select><select id="kind" aria-label="Tipo"><option value="">Todos los tipos</option><option value="walking_connection">Conexión peatonal</option><option value="internal_interchange">Misma estación</option><option value="interchange_unspecified">Intercambio de acceso no especificado</option><option value="mode_connection">Otro modo o servicio</option><option value="restrictions">Restricciones y servicio</option></select><input id="search" aria-label="Buscar" placeholder="Buscar estación, stop_id o servicio"></div>
<main><section class="panel"><h2 id="maptitle"></h2><div class="map"><img id="mapimg" alt="Mapa oficial Renfe del núcleo seleccionado"><svg id="overlay"></svg></div><p class="source" id="source"></p></section><section class="panel"><h2 id="count"></h2><div class="results"><table><thead><tr><th>Estación / conexión</th><th>Tipo</th><th>stop_id</th></tr></thead><tbody id="rows"></tbody></table></div><div class="detail" id="detail">Selecciona una fila para ver la región de evidencia sobre el mapa.</div><p class="note" id="coverage"></p></section></main>
<footer class="panel"><h2>Datos y alcance</h2><p><a href="data/routing-corrections.proposed.json">Propuesta de conexiones para la app</a>: conserva la separación entre estación y apeadero de Los Rosales y la política estimada de transbordo. <a href="data/routing_overlay.json">Auditoría de puntos de embarque</a>.</p><p><a href="data/connections.json">JSON de observaciones</a> · <a href="data/connections.csv">CSV de observaciones</a> · <a href="data/pedestrian_observations.csv">CSV de todos los enlaces peatonales</a> · <a href="data/station_symbols.json">Símbolos y propuestas de asociación</a> · <a href="data/gtfs_transfers.csv">Transferencias del GTFS</a> · <a href="data/coverage.csv">Cobertura por núcleo</a> · <a href="SUMMARY.md">Cómo reproducirlo</a></p>
<p>Los cinco enlaces peatonales entre estaciones distintas tienen la indicación «menos de 10 minutos a pie». Ninguno figura entre los tres pares de estaciones distintas de transfers.txt. El sexto pictograma está en Los Rosales (C-1 / C-3, stop_id 50700): el extremo C-3 no lleva nombre en el plano. El mapa oficial de febrero de 2025 lo identifica como Los Rosales Apeadero. Hay un paseo entre estación y apeadero; el GTFS los agrupa bajo 50700. No debe suponerse un cambio inmediato de andén. Se conserva <code>min_transfer_time_seconds = null</code>: un límite superior cartográfico no es un mínimo de transbordo.</p>
<p>«Misma estación» incluye las cápsulas gráficas en tramos compartidos, no solo grandes nodos. Maliaño / Maliaño La Vidriera permanece como intercambio de acceso no especificado. Los iconos de otro servicio no identifican necesariamente una estación destino ni un recorrido interior.</p>
<p class="note">Pipeline semiautomático: extracción geométrica reproducible + anotaciones revisadas y fijadas a la huella de cada PDF y GTFS. Los símbolos complementarios de aparcamiento, accesibilidad, bicicletas y tarifas conservan asociaciones automáticas pendientes. La revisión de 15 mapas no certifica exhaustividad de la extracción automática. Los mapas reflejan su propia edición; no sustituyen avisos ni horarios actuales.</p>
<details><summary>Limitaciones y excepciones concretas</summary><p>Alcantarilla Los Romanos figura en el plano de Murcia/Alicante pero no tiene correspondencia identificada en el GTFS descargado. Barcelona contiene numerosos rótulos como contornos: su revisión utiliza regiones anotadas visualmente. El logotipo Euskotren de San Sebastián requiere anotación complementaria. Las cajas manuales son regiones de evidencia, no contornos exactos del símbolo.</p><p>Río Arillo: sin acceso exterior, solo transbordo. León: lanzadera de autobús. Murcia–Águilas: servicio interrumpido según el mapa. C-4 Sevilla: sentido indicado por flechas. Balenyà-Tona-Seva: asterisco de estación sin viajeros en la edición 12/2024. Ninguno de estos estados se presenta como verificación en tiempo real.</p></details>
<details><summary>Reproducción e integración</summary><pre>python -m pip install -r requirements.txt
python acquire.py
python pipeline.py all
python -m unittest -v
python review.py</pre><p><code>acquire.py --refresh</code> consulta de nuevo las páginas oficiales. Si cambia el mapa o el GTFS, el compilador exige revisar las anotaciones. Para el router, conservar transfers.txt con sus restricciones de ruta/viaje y precedencia; utilizar estos datos como una capa de evidencia. No activar enlaces sin una política explícita de duración y acceso.</p></details>
</footer><script id="dataset" type="application/json">__DATA__</script><script>
const D=JSON.parse(document.getElementById('dataset').textContent),$=id=>document.getElementById(id);let selected=null;
const types={internal_interchange:'Misma estación',walking_connection:'A pie',interchange_unspecified:'Acceso por determinar',mode_connection:'Modo / servicio',station_restriction:'Acceso',service_interruption:'Interrupción',replacement_bus:'Lanzadera',directional_service:'Sentido',no_passenger_service:'Sin viajeros (mapa)'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('total').textContent=D.records.length;$('core').innerHTML=D.maps.map(m=>`<option value="${m.core}">${esc(m.core)}</option>`).join('');$('core').value='bilbao';
function render(){const core=$('core').value,m=D.maps.find(m=>m.core===core),cov=D.coverage.find(c=>c.core===core),q=$('search').value.toLowerCase(),kind=$('kind').value;
const rows=D.records.filter(r=>r.core===core&&(!kind||(kind==='walking_connection'?Boolean(r.pedestrian_link):kind==='restrictions'?!['internal_interchange','walking_connection','interchange_unspecified','mode_connection'].includes(r.kind):r.kind===kind))&&JSON.stringify([r.map_label,r.stop_ids,r.mode,r.connecting_services]).toLowerCase().includes(q));
$('maptitle').textContent='Mapa oficial · '+core;$('mapimg').src=m.preview;$('overlay').setAttribute('viewBox',`0 0 ${m.width} ${m.height}`);$('overlay').innerHTML='';$('source').innerHTML=`<a href="${esc(m.url)}">Fuente Renfe</a> · <a href="${esc(m.file)}">PDF conservado</a><br>SHA-256: ${esc(m.sha256)}`;
$('count').textContent=rows.length+' observaciones';$('rows').innerHTML=rows.map(r=>`<tr data-id="${esc(r.id)}"><td><button>${esc(r.map_label)}</button><br><small>${esc((r.connecting_services||[]).join(', ')||r.mode||'')}</small></td><td><span class="badge">${esc(r.pedestrian_link?'A pie':types[r.kind])}</span></td><td>${esc(r.stop_ids.join(' ↔ ')||'Sin correspondencia')}</td></tr>`).join('');
$('coverage').textContent=`${cov.reviewed_records} observaciones revisadas; ${cov.symbol_candidates} símbolos detectados automáticamente; ${cov.symbol_associations_pending} asociaciones complementarias pendientes. ${cov.reviewed_records_missing_gtfs} observaciones sin stop_id.`;$('detail').textContent='Selecciona una fila para ver su evidencia.';
document.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>show(D.records.find(r=>r.id===tr.dataset.id),tr));}
function show(r,tr){document.querySelectorAll('tr.selected').forEach(x=>x.classList.remove('selected'));tr.classList.add('selected');const [x,y,x2,y2]=r.bbox,pad=8;$('overlay').innerHTML=`<rect x="${x-pad}" y="${y-pad}" width="${x2-x+2*pad}" height="${y2-y+2*pad}"/>`;
$('detail').innerHTML=`<b>${esc(r.map_label)}</b><p>${esc(r.notes)}</p><p>${r.gtfs_stops.map(s=>esc(s.stop_id+' · '+s.stop_name)).join('<br>')||'Sin correspondencia identificada en esta captura.'}</p><p>Página ${r.page} · ${esc(r.id)} · ${esc(r.gtfs_match_status)}</p>${r.pedestrian_link?'<p>Menos de 600 s según leyenda; tiempo mínimo desconocido.</p>':''}<p>Reglas GTFS relacionadas: ${r.matching_gtfs_transfer_rows.length}. Uso directo por router: desactivado.</p>`;}
['core','kind','search'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));render();
</script></html>'''
    (ROOT/'index.html').write_text(template.replace('__DATA__',payload),encoding='utf-8')
    print('Viewer built:',ROOT/'index.html')
if __name__=='__main__':main()

