name: Validate
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  pipeline:
    uses: ./.github/workflows/publish.yml
    with:
      revision: ${{ github.sha }}
      publish: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
