name: Validate
on: [push, pull_request]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  pipeline:
    uses: ./.github/workflows/publish.yml
    with:
      revision: ${{ github.sha }}
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
